# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCLlpcflpWeBXz42AJxNMk_UpAb5iy4o
"""

import streamlit as st
from PIL import Image
import os
from digit_generator import generate_images_for_digit

st.title("MNIST Digit Generator")

digit = st.selectbox("Choose a digit to generate (0-9):", list(range(10)))

if st.button("Generate Digit Images"):
    generate_images_for_digit(digit)
    st.write(f"Generated 5 images of digit: {digit}")
    for i in range(5):
        img_path = f"generated_images/{digit}_{i}.png"
        st.image(Image.open(img_path), width=100)