# -*- coding: utf-8 -*-
"""digit_generator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCLlpcflpWeBXz42AJxNMk_UpAb5iy4o
"""

import os
import random
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

def generate_images_for_digit(digit, save_path='generated_images'):
    os.makedirs(save_path, exist_ok=True)
    transform = transforms.Compose([transforms.ToTensor()])
    dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

    samples = [img for img, label in dataset if label == digit]
    random.shuffle(samples)
    for i, img in enumerate(samples[:5]):
        plt.imsave(f"{save_path}/{digit}_{i}.png", img.squeeze(), cmap='gray')